package com.tyhoo.android.mvvm.base

const val TAG = "Tyhoo_MVVM"

var HERO_LIST_FIRST_VISIBLE_ITEM_POSITION = 0
var HERO_LIST_OFFSET = 0

var EQUIPMENT_LIST_FIRST_VISIBLE_ITEM_POSITION = 0
var EQUIPMENT_LIST_OFFSET = 0

var ARCANA_LIST_FIRST_VISIBLE_ITEM_POSITION = 0
var ARCANA_LIST_OFFSET = 0